# Generated by Django 4.0.3 on 2022-04-09 01:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_app', '0008_remove_appuser_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_number', models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('flight_code', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)])),
                ('flight_from', models.CharField(max_length=30)),
                ('flight_to', models.CharField(max_length=30)),
                ('flight_cost', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('flight_time', models.DateTimeField()),
            ],
            options={
                'ordering': ['flight_number'],
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=187)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bookings', models.ManyToManyField(to='web.flight')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_from', models.BooleanField(max_length=25)),
                ('to', models.BooleanField(max_length=25)),
                ('date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport', models.CharField(blank=True, max_length=52, null=True)),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.town')),
            ],
        ),
    ]
