# Generated by Django 4.0.3 on 2022-04-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_flight_flight_from_alter_flight_flight_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_from',
            field=models.CharField(choices=[(5, 'Sofia'), (6, 'Berlin'), (7, 'London')], max_length=30),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_to',
            field=models.CharField(choices=[(5, 'Sofia'), (6, 'Berlin'), (7, 'London')], max_length=30),
        ),
    ]
