# Generated by Django 4.0.3 on 2022-04-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_flight_flight_from_alter_flight_flight_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_from',
            field=models.CharField(choices=[('Sofia', 'Sofia'), ('Berlin', 'Berlin'), ('London', 'London'), ('Reading', 'Reading'), ('Skopije', 'Skopije')], max_length=30),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_to',
            field=models.CharField(choices=[('Sofia', 'Sofia'), ('Berlin', 'Berlin'), ('London', 'London'), ('Reading', 'Reading'), ('Skopije', 'Skopije')], max_length=30),
        ),
    ]
