# Generated by Django 4.0.3 on 2022-04-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_flight_flight_code_alter_flight_flight_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_from',
            field=models.CharField(choices=[], max_length=30),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_to',
            field=models.CharField(choices=[], max_length=30),
        ),
    ]
