# Generated by Django 4.0.3 on 2022-04-13 04:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_remove_appuser_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, max_length=2, null=True, validators=[django.core.validators.MinValueValidator(18)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='passport',
            field=models.IntegerField(blank=True, max_length=9, null=True, validators=[django.core.validators.MinValueValidator(100000000, message='Ensure your Passport ID is 9 digits.')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
