# Generated by Django 4.0.3 on 2022-04-13 04:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_profile_age_profile_passport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passport',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100000000, message='Ensure your Passport ID is 9 digits.')]),
        ),
    ]
