# Generated by Django 4.0.3 on 2022-04-13 04:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_alter_profile_age_alter_profile_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='passport',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100000000, message='Ensure your Passport ID is 9 digits.'), django.core.validators.MaxValueValidator(999999999, message='Ensure your Passport ID is 9 digits.')]),
        ),
    ]
