# Generated by Django 4.0.3 on 2022-04-07 01:20

import TimeToFly.web.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[TimeToFly.web.validators.MaxFileSize(1)]),
        ),
    ]
