# Generated by Django 4.0.3 on 2022-04-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_deleted',
            field=models.BooleanField(default=True),
        ),
    ]
