# Generated by Django 4.0.3 on 2022-04-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_booking_depart_from_alter_booking_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_from',
            field=models.CharField(choices=[], max_length=30),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_to',
            field=models.CharField(choices=[], max_length=30),
        ),
    ]
