# Generated by Django 4.0.3 on 2022-04-09 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_flight_flight_from_alter_flight_flight_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_code',
            field=models.CharField(max_length=6, unique=True, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_from',
            field=models.CharField(choices=[('Sofia', 'Sofia'), ('London', 'London'), ('Berlin', 'Berlin')], max_length=30),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_to',
            field=models.CharField(choices=[('Sofia', 'Sofia'), ('London', 'London'), ('Berlin', 'Berlin')], max_length=30),
        ),
    ]
