# Generated by Django 4.0.3 on 2022-04-10 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_flight_flight_from_alter_flight_flight_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Airport',
        ),
    ]
