# Generated by Django 4.0.3 on 2022-04-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_passenger_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='selected',
            field=models.CharField(blank=True, max_length=287, null=True),
        ),
    ]
