# Generated by Django 4.0.3 on 2022-04-13 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_passenger_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='selected',
        ),
    ]
