# Generated by Django 4.0.3 on 2022-04-16 01:42

import TimeToFly.web.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_flight_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_time',
            field=models.DateTimeField(validators=[TimeToFly.web.validators.MinDateValidator]),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
