# Generated by Django 4.0.3 on 2022-04-16 01:47

import TimeToFly.web.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_alter_flight_flight_time_delete_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_time',
            field=models.DateTimeField(validators=[TimeToFly.web.validators.MinDateValidator(datetime.date)]),
        ),
    ]
