# Generated by Django 4.0.3 on 2022-04-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_alter_flight_flight_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='town',
            options={'ordering': ['town']},
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_from',
            field=models.CharField(choices=[('Amsterdam', 'Amsterdam'), ('Beograd', 'Beograd'), ('Berlin', 'Berlin'), ('Bourgas', 'Bourgas'), ('Budapest', 'Budapest'), ('Lisbon', 'Lisbon'), ('London', 'London'), ('Luxemburg', 'Luxemburg'), ('Madrid', 'Madrid'), ('Oslo', 'Oslo'), ('Paris', 'Paris'), ('Rome', 'Rome'), ('Skopije', 'Skopije'), ('Sofia', 'Sofia'), ('Thessaloniki', 'Thessaloniki'), ('Varna', 'Varna')], max_length=30),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_to',
            field=models.CharField(choices=[('Amsterdam', 'Amsterdam'), ('Beograd', 'Beograd'), ('Berlin', 'Berlin'), ('Bourgas', 'Bourgas'), ('Budapest', 'Budapest'), ('Lisbon', 'Lisbon'), ('London', 'London'), ('Luxemburg', 'Luxemburg'), ('Madrid', 'Madrid'), ('Oslo', 'Oslo'), ('Paris', 'Paris'), ('Rome', 'Rome'), ('Skopije', 'Skopije'), ('Sofia', 'Sofia'), ('Thessaloniki', 'Thessaloniki'), ('Varna', 'Varna')], max_length=30),
        ),
    ]
